permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: write
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'chrodium version'
        required: true
        default: ''
      target_os:
        description: 'target [android/linux/all]'
        required: true
        default: 'all'
      build:
        description: 'android arch [arm/arm64/x64/all]'
        required: true
        default: 'all'
      type:
        description: 'runner? [dev/cli/ubuntu-latest]'
        required: false
        default: 'ci'
      debug:
        description: 'debug? [true/false]'
        required: false
        default: 'false'
      clangd:
        description: 'clangd? [true/false]'
        required: true
        default: 'false'

env:
  CHR_VERSION: ${{ github.event.inputs.version }}
  REMOVEDOCKERSUPPORT: true
  USELOCALIMAGE: true

name: Check images build and push to Dockerhub
jobs:
  check_images:
    name: Generate Build Images
    runs-on: ${{ github.event.inputs.type }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: chrodium
          fetch-depth: 1

      - name: Enable proxy on container
        shell: bash
        run: |
          if ! [[ -z "${HTTP_PROXY}" ]]; then
            PROXY_ADDR=http://$(hostname -I | cut -d' ' -f1 | xargs):8118
            echo "PROXY_ADDR=$PROXY_ADDR" >> $GITHUB_ENV
            sudo iptables -D INPUT -p tcp -s localhost --dport 8118 -j ACCEPT
            sudo iptables -D INPUT -p tcp --dport 8118 -j DROP
          fi
      - name: Download regctl
        shell: bash
        run: |
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
          chmod 755 regctl
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current chromium version
        shell: bash
        run: |
          export VERSION=$(cat ./chrodium/images/RELEASE)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check versions
        shell: bash
        run: |
          if [ -z $CHR_VERSION ]; then
            LATEST_WIN=$(curl -s 'https://versionhistory.googleapis.com/v1/chrome/platforms/win64/channels/stable/versions/all/releases'  | jq -rc '.releases[].version' | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -n 1)
            LATEST_ANDROID=$(curl -s 'https://versionhistory.googleapis.com/v1/chrome/platforms/android/channels/stable/versions/all/releases'  | jq -rc '.releases[].version' | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -n 1)
            CHR_VERSION=$(echo -e "$LATEST_ANDROID\n$LATEST_WIN" | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -n 1)

            echo "LATEST_WIN=$LATEST_WIN" >> $GITHUB_ENV
            echo "LATEST_ANDROID=$LATEST_ANDROID" >> $GITHUB_ENV
            echo "CHR_VERSION=$CHR_VERSION" >> $GITHUB_ENV
          fi

      - name: Building build-deps container ${{ env.VERSION }}
        shell: bash
        run: |
          IS_PRESENT=$(docker inspect --type=image rigel254/build-deps:$CHR_VERSION > /dev/null ; echo $?)
          if [ $IS_PRESENT -ne "0" ]; then
            IS_PRESENT=$(./regctl image inspect rigel254/build-deps:$CHR_VERSION > /dev/null ; echo $?)
            if [ $IS_PRESENT -ne "0" ]; then
              DOCKER_BUILDKIT=1 docker build -t rigel254/build-deps:$CHR_VERSION \
                --progress plain \
                --build-arg VERSION=$CHR_VERSION \
                --build-arg HTTP_PROXY="$PROXY_ADDR" \
                --no-cache \
                chrodium/images/build-deps/.

              docker push rigel254/build-deps:$CHR_VERSION
            fi
          fi

      - name: Building chromium container ${{ env.VERSION }}
        shell: bash
        run: |
          IS_PRESENT=$(docker inspect --type=image rigel254/chromium:$CHR_VERSION > /dev/null ; echo $?)
          if [ $IS_PRESENT -ne "0" ]; then
            IS_PRESENT=$(./regctl image inspect rigel254/chromium:$CHR_VERSION > /dev/null ; echo $?)
            if [ $IS_PRESENT -ne "0" ]; then
              DOCKER_BUILDKIT=1 docker build -t rigel254/chromium:$CHR_VERSION \
                --progress plain \
                --build-arg VERSION=$CHR_VERSION \
                --build-arg HTTP_PROXY="$PROXY_ADDR" \
                chrodium/images/chr-source/.

              docker push rigel254/chromium:$CHR_VERSION
            fi
          fi

      - name: Get rigel254/chromium from docker hub
        shell: bash
        run: |
          IS_PRESENT=$(./regctl image inspect rigel25/chromium:$CHR_VERSION > /dev/null ; echo $?)
          if [ $IS_PRESENT -eq "0" ]; then
            docker pull rigel254/chromium:$CHR_VERSION
          fi

      - name: Mark image to build
        shell: bash
        run: |
          IS_PRESENT=$(docker inspect --type=image rigel254/chromium:$CHR_VERSION > /dev/null ; echo $?)
          if [ $IS_PRESENT -eq "0" ]; then
            docker rmi uazo/chromium:$CHR_VERSION
          fi
        docker tag rigel254/chromium:$CHR_VERSION rigel254/chrodium:build

  build_chrodium:
    runs-on: ${{ github.event.inputs.type }}
    needs: check_images
    if: success() 
    timeout-minutes: 1440

    container:
      image: rigel254/chrodium:build
      env:
        REMOVEDOCKERSUPPORT: true # CUSTOM RUNNER: remove sharing of docker socket
        USELOCALIMAGE: true       # CUSTOM RUNNER: permit use of local images
        USEINTERNALNETWORK: true  # CUSTOM RUNNER: create the docker network as internal
        WORKSPACE: /home/lg/working_dir
        # kythe
        # KYTHE_CORPUS: chromium.googlesource.com/chromium/src
        # KYTHE_ROOT_DIRECTORY: /home/lg/working_dir/chromium/src
        # KYTHE_OUTPUT_DIRECTORY: /home/lg/working_dir/chromium/src/out/arm64/kythe
        # cross build
        # DEPOT_TOOLS_WIN_TOOLCHAIN_BASE_URL: /win_sdk/sdks/Win11SDK_10.0.26100.0/
        # WINDOWSSDKDIR: "/win_sdk/sdks/Win11SDK_10.0.26100.0/Windows Kits/10/"
        # GYP_MSVS_OVERRIDE_PATH: /win_sdk/sdks/Win11SDK_10.0.26100.0/
        # compile in debug mode
        TARGET_ISDEBUG: ${{ github.event.inputs.debug }}
        TARGET_OS: ${{ github.event.inputs.target_os }}
        USE_KEYSTORE: true
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        # CROMITE_PREF_HASH_SEED_BIN: ${{ secrets.CROMITE_PREF_HASH_SEED_BIN }}
      volumes:
        - /storage/images/${{ github.event.inputs.sha }}/android/${{ github.event.inputs.debug }}/arm:/home/lg/working_dir/chromium/src/out/arm
        - /storage/images/${{ github.event.inputs.sha }}/android/${{ github.event.inputs.debug }}/arm64:/home/lg/working_dir/chromium/src/out/arm64
        - /storage/images/${{ github.event.inputs.sha }}/android/${{ github.event.inputs.debug }}/x64:/home/lg/working_dir/chromium/src/out/x64
        - /storage/images/${{ github.event.inputs.sha }}/linux/${{ github.event.inputs.debug }}/lin64:/home/lg/working_dir/chromium/src/out/lin64
        # - /storage/images/${{ github.event.inputs.sha }}/win/x64:/home/lg/working_dir/chromium/src/out/win64
        - /tmp/proxy:/tmp/proxy
        # - /win_sdk:/win_sdk
        
    steps:
      - name: Prepare Build container
        shell: bash
        run: |
          ls -al 
          git --version


