# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          distribution: "temurin"

      # Runs a set of commands using the runners shell
      - name: Generate keystore
        run: |
          keytool -genkey -v -storepass "${{secrets.CHRODIUM_KEY}}" -keystore vanadium.keystore -storetype pkcs12 -alias vanadium -keyalg RSA -keysize 4096 -sigalg SHA512withRSA -validity 10000 -dname "cn=GrapheneOS"

      - name: Verify keystore
        run: |
          keytool -v -list -keystore vanadium.keystore -storepass "${{secrets.CHRODIUM_KEY}}"

      - name: install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:$PWD/depot_tools"
          fetch --nohooks android
      - name: install depot_tools & fetch chromium
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:$PWD/depot_tools"
          fetch --nohooks --no-history android 
      - name: applying vanadium patch
        run: |
          cd src
          git fetch --tags
          git tag -l
          echo "CHECK TAG"
          echo "-------------------"
          git describe --tags $(git rev-list --tags --max-count=1)
          echo "-------------------"
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
          git am --whitespace=nowarn --keep-non-patch ../patches/*.patch
          gclient sync -D --with_branch_heads --with_tags --jobs 32
          gn args out/Default

